import type { BlockDefinition, ScaleDefinition } from "@/types/assessment";

import {
  BIG_FIVE_CODES_SOURCE_URL,
  BIG_FIVE_RUSSIAN_SOURCE_URL,
  BIG_FIVE_SOURCE,
} from "@/content/tests/version";

const BIG_FIVE_SCALES: ScaleDefinition[] = [
  {
    key: "openness-to-new",
    blockId: "big-five",
    label: "Открытость новому",
    shortLabel: "Открытость",
    scientificLabel: "Intellect / Imagination (Factor V)",
    description:
      "Тяга к идеям, воображению, абстракциям и исследованию новых подходов.",
    type: "core",
    sourceScale: "IPIP Big-Five Factor V",
  },
  {
    key: "conscientiousness",
    blockId: "big-five",
    label: "Добросовестность",
    shortLabel: "Добросовестность",
    scientificLabel: "Conscientiousness",
    description:
      "Степень организованности, дисциплины, точности и устойчивости к хаосу.",
    type: "core",
    sourceScale: "IPIP Big-Five Factor III",
  },
  {
    key: "extraversion",
    blockId: "big-five",
    label: "Общительность / экстраверсия",
    shortLabel: "Экстраверсия",
    scientificLabel: "Extraversion",
    description:
      "Выраженность внешней энергии, разговорчивости и социального включения.",
    type: "core",
    sourceScale: "IPIP Big-Five Factor I",
  },
  {
    key: "agreeableness",
    blockId: "big-five",
    label: "Доброжелательность",
    shortLabel: "Доброжелательность",
    scientificLabel: "Agreeableness",
    description:
      "Склонность к сочувствию, мягкости и учету чувств других людей.",
    type: "core",
    sourceScale: "IPIP Big-Five Factor II",
  },
  {
    key: "emotional-sensitivity",
    blockId: "big-five",
    label: "Эмоциональная чувствительность",
    shortLabel: "Чувствительность",
    scientificLabel: "Neuroticism (displayed via Emotional Stability source factor)",
    description:
      "Интенсивность стресса, тревоги, раздражительности и эмоциональной уязвимости.",
    type: "core",
    sourceScale: "IPIP Big-Five Factor IV (Emotional Stability source scale, inverted for display)",
  },
];

function question(
  itemId: string,
  order: number,
  originalText: string,
  russianText: string,
  scaleKey: string,
  scientificScale: string,
  reverseKeyed: boolean,
) {
  return {
    blockId: "big-five" as const,
    itemId,
    order,
    originalText,
    russianText,
    scaleKey,
    scientificScale,
    reverseKeyed,
    source: {
      ...BIG_FIVE_SOURCE,
      usageNotes: `${BIG_FIVE_SOURCE.usageNotes} Question codes are aligned with ${BIG_FIVE_CODES_SOURCE_URL}; Russian wording follows ${BIG_FIVE_RUSSIAN_SOURCE_URL}.`,
    },
  };
}

export const BIG_FIVE_BLOCK: BlockDefinition = {
  id: "big-five",
  order: 1,
  title: "Большая пятёрка",
  subtitle: "Открытый IPIP-маркер на 50 вопросов",
  description:
    "Блок собирает базовый профиль по пяти широким личностным факторам на основе открытого IPIP-опросника.",
  disclosure:
    "Это открытый лексический опросник личности. Он показывает выраженность паттернов, а не ставит диагнозы и не обещает «объективную истину» о человеке.",
  scales: BIG_FIVE_SCALES,
  questions: [
    question(
      "H34",
      1,
      "Am the life of the party.",
      "Вы душа компании.",
      "extraversion",
      "Extraversion",
      false,
    ),
    question(
      "H37R",
      2,
      "Feel little concern for others.",
      "Вы мало беспокоитесь о других.",
      "agreeableness",
      "Agreeableness",
      true,
    ),
    question(
      "H13",
      3,
      "Am always prepared.",
      "Вы обычно готовы заранее.",
      "conscientiousness",
      "Conscientiousness",
      false,
    ),
    question(
      "H4",
      4,
      "Get stressed out easily.",
      "Вы легко подвергаетесь стрессу.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H8",
      5,
      "Have a rich vocabulary.",
      "У вас богатый словарный запас.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
    question(
      "H26",
      6,
      "Don't talk a lot.",
      "Вы не говорите много.",
      "extraversion",
      "Extraversion",
      true,
    ),
    question(
      "H41",
      7,
      "Am interested in people.",
      "Люди вам интересны.",
      "agreeableness",
      "Agreeableness",
      false,
    ),
    question(
      "H18R",
      8,
      "Leave my belongings around.",
      "Вы часто разбрасываете вещи.",
      "conscientiousness",
      "Conscientiousness",
      true,
    ),
    question(
      "H10R",
      9,
      "Am relaxed most of the time.",
      "Обычно вы спокойны и расслаблены.",
      "emotional-sensitivity",
      "Neuroticism",
      true,
    ),
    question(
      "H11R",
      10,
      "Have difficulty understanding abstract ideas.",
      "Вам сложно понимать абстрактные идеи.",
      "openness-to-new",
      "Intellect / Imagination",
      true,
    ),
    question(
      "H67R",
      11,
      "Feel comfortable around people.",
      "Вы чувствуете себя комфортно среди людей.",
      "extraversion",
      "Extraversion",
      false,
    ),
    question(
      "H46R",
      12,
      "Insult people.",
      "Вы можете оскорбить человека.",
      "agreeableness",
      "Agreeableness",
      true,
    ),
    question(
      "H22",
      13,
      "Pay attention to details.",
      "Вы обращаете внимание на детали.",
      "conscientiousness",
      "Conscientiousness",
      false,
    ),
    question(
      "H6R",
      14,
      "Worry about things.",
      "Вы часто беспокоитесь о вещах.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H15",
      15,
      "Have a vivid imagination.",
      "У вас живое воображение.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
    question(
      "H63R",
      16,
      "Keep in the background.",
      "Вы предпочитаете держаться в тени.",
      "extraversion",
      "Extraversion",
      true,
    ),
    question(
      "H51",
      17,
      "Sympathize with others' feelings.",
      "Вы сочувствуете чувствам других.",
      "agreeableness",
      "Agreeableness",
      false,
    ),
    question(
      "H27",
      18,
      "Make a mess of things.",
      "Вы создаёте беспорядок.",
      "conscientiousness",
      "Conscientiousness",
      true,
    ),
    question(
      "H14R",
      19,
      "Seldom feel blue.",
      "Вы редко бываете подавлены.",
      "emotional-sensitivity",
      "Neuroticism",
      true,
    ),
    question(
      "H20",
      20,
      "Am not interested in abstract ideas.",
      "Вас не интересуют абстрактные идеи.",
      "openness-to-new",
      "Intellect / Imagination",
      true,
    ),
    question(
      "H79R",
      21,
      "Start conversations.",
      "Вы часто начинаете разговор сами.",
      "extraversion",
      "Extraversion",
      false,
    ),
    question(
      "H54R",
      22,
      "Am not interested in other people's problems.",
      "Вам неинтересны чужие проблемы.",
      "agreeableness",
      "Agreeableness",
      true,
    ),
    question(
      "H30R",
      23,
      "Get chores done right away.",
      "Вы сразу доводите бытовые дела до конца.",
      "conscientiousness",
      "Conscientiousness",
      false,
    ),
    question(
      "H16R",
      24,
      "Am easily disturbed.",
      "Вас легко вывести из равновесия.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H23",
      25,
      "Have excellent ideas.",
      "У вас часто возникают отличные идеи.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
    question(
      "H75R",
      26,
      "Have little to say.",
      "Вы немногословны.",
      "extraversion",
      "Extraversion",
      true,
    ),
    question(
      "H58R",
      27,
      "Have a soft heart.",
      "У вас мягкое сердце.",
      "agreeableness",
      "Agreeableness",
      false,
    ),
    question(
      "H35",
      28,
      "Often forget to put things back in their proper place.",
      "Вы часто забываете положить вещи на место.",
      "conscientiousness",
      "Conscientiousness",
      true,
    ),
    question(
      "H24R",
      29,
      "Get upset easily.",
      "Вы легко расстраиваетесь.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H53R",
      30,
      "Do not have a good imagination.",
      "У вас не очень хорошее воображение.",
      "openness-to-new",
      "Intellect / Imagination",
      true,
    ),
    question(
      "H83",
      31,
      "Talk to a lot of different people at parties.",
      "На встречах и вечеринках вы говорите со многими разными людьми.",
      "extraversion",
      "Extraversion",
      false,
    ),
    question(
      "H61",
      32,
      "Am not really interested in others.",
      "На самом деле люди вам не особенно интересны.",
      "agreeableness",
      "Agreeableness",
      true,
    ),
    question(
      "H39R",
      33,
      "Like order.",
      "Вы любите порядок.",
      "conscientiousness",
      "Conscientiousness",
      false,
    ),
    question(
      "H28R",
      34,
      "Change my mood a lot.",
      "У вас часто меняется настроение.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H29",
      35,
      "Am quick to understand things.",
      "Вы быстро вникаете в суть вещей.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
    question(
      "H90",
      36,
      "Don't like to draw attention to myself.",
      "Вы не любите привлекать к себе внимание.",
      "extraversion",
      "Extraversion",
      true,
    ),
    question(
      "H69R",
      37,
      "Take time out for others.",
      "Вы находите время для других.",
      "agreeableness",
      "Agreeableness",
      false,
    ),
    question(
      "H43R",
      38,
      "Shirk my duties.",
      "Вы уклоняетесь от обязанностей.",
      "conscientiousness",
      "Conscientiousness",
      true,
    ),
    question(
      "H31R",
      39,
      "Have frequent mood swings.",
      "Вы подвержены частым перепадам настроения.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H32R",
      40,
      "Use difficult words.",
      "Вы используете сложные слова.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
    question(
      "H87R",
      41,
      "Don't mind being the center of attention.",
      "Вы не возражаете быть в центре внимания.",
      "extraversion",
      "Extraversion",
      false,
    ),
    question(
      "H73R",
      42,
      "Feel others' emotions.",
      "Вы чувствуете эмоции окружающих.",
      "agreeableness",
      "Agreeableness",
      false,
    ),
    question(
      "H48R",
      43,
      "Follow a schedule.",
      "Вы придерживаетесь распорядка.",
      "conscientiousness",
      "Conscientiousness",
      false,
    ),
    question(
      "H42R",
      44,
      "Get irritated easily.",
      "Вы легко раздражаетесь.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H44",
      45,
      "Spend time reflecting on things.",
      "Вы останавливаетесь, чтобы обдумать происходящее.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
    question(
      "H93",
      46,
      "Am quiet around strangers.",
      "С незнакомыми людьми вы ведёте себя тихо.",
      "extraversion",
      "Extraversion",
      true,
    ),
    question(
      "H76R",
      47,
      "Make people feel at ease.",
      "Рядом с вами людям легко и спокойно.",
      "agreeableness",
      "Agreeableness",
      false,
    ),
    question(
      "H55",
      48,
      "Am exacting in my work.",
      "Вы аккуратны и требовательны к своей работе.",
      "conscientiousness",
      "Conscientiousness",
      false,
    ),
    question(
      "H50R",
      49,
      "Often feel blue.",
      "Вы часто чувствуете грусть или упадок.",
      "emotional-sensitivity",
      "Neuroticism",
      false,
    ),
    question(
      "H47",
      50,
      "Am full of ideas.",
      "Вы полны идей.",
      "openness-to-new",
      "Intellect / Imagination",
      false,
    ),
  ],
};
