import type { BlockDefinition, ScaleDefinition } from "@/types/assessment";

import {
  IPIP_IPC_ANGLE_REFERENCE_URL,
  IPIP_IPC_SCORING_SOURCE_URL,
  IPIP_IPC_SOURCE,
} from "@/content/tests/version";

const IPIP_IPC_SCALES: ScaleDefinition[] = [
  {
    key: "PA",
    blockId: "ipip-ipc",
    label: "Напористо-доминирующий сектор",
    shortLabel: "PA",
    scientificLabel: "Assured-Dominant",
    description: "Инициативность, сила предъявления и готовность занимать ведущую позицию.",
    type: "core",
    sourceScale: "PA",
  },
  {
    key: "BC",
    blockId: "ipip-ipc",
    label: "Жёстко-конфронтационный сектор",
    shortLabel: "BC",
    scientificLabel: "Arrogant-Calculating",
    description: "Жёсткость, спорность, колкость и привычка давить в общении.",
    type: "core",
    sourceScale: "BC",
  },
  {
    key: "DE",
    blockId: "ipip-ipc",
    label: "Холодно-дистанционный сектор",
    shortLabel: "DE",
    scientificLabel: "Cold-Hearted",
    description: "Эмоциональная дистанция, автономность и низкая включённость в чужие переживания.",
    type: "core",
    sourceScale: "DE",
  },
  {
    key: "FG",
    blockId: "ipip-ipc",
    label: "Сдержанно-интровертный сектор",
    shortLabel: "FG",
    scientificLabel: "Aloof-Introverted",
    description: "Закрытость, приватность и снижение внешней социальной заметности.",
    type: "core",
    sourceScale: "FG",
  },
  {
    key: "HI",
    blockId: "ipip-ipc",
    label: "Неуверенно-подстраивающийся сектор",
    shortLabel: "HI",
    scientificLabel: "Unassured-Submissive",
    description: "Сдержанность в самопредъявлении и склонность уступать инициативу другим.",
    type: "core",
    sourceScale: "HI",
  },
  {
    key: "JK",
    blockId: "ipip-ipc",
    label: "Негромко-уступчивый сектор",
    shortLabel: "JK",
    scientificLabel: "Unassuming-Ingenuous",
    description: "Мягкость, терпение и готовность не продавливать свою линию.",
    type: "core",
    sourceScale: "JK",
  },
  {
    key: "LM",
    blockId: "ipip-ipc",
    label: "Тёпло-доброжелательный сектор",
    shortLabel: "LM",
    scientificLabel: "Warm-Agreeable",
    description: "Контактность, внимательность к людям и поддерживающий стиль взаимодействия.",
    type: "core",
    sourceScale: "LM",
  },
  {
    key: "NO",
    blockId: "ipip-ipc",
    label: "Социально-экспрессивный сектор",
    shortLabel: "NO",
    scientificLabel: "Gregarious-Extraverted",
    description: "Лёгкость в контакте, видимость в группе и живое социальное включение.",
    type: "core",
    sourceScale: "NO",
  },
  {
    key: "dominance-axis",
    blockId: "ipip-ipc",
    label: "Доминирование / подстройка",
    shortLabel: "Доминирование",
    scientificLabel: "Dominance axis",
    description:
      "Проекция восьми секторов на вертикальную ось IPC: сверху более доминирующий стиль, снизу более подстраивающийся.",
    type: "derived",
  },
  {
    key: "warmth-axis",
    blockId: "ipip-ipc",
    label: "Теплота / дистанция",
    shortLabel: "Теплота",
    scientificLabel: "Warmth axis",
    description:
      "Проекция восьми секторов на горизонтальную ось IPC: слева более тёплый стиль, справа более дистанционный.",
    type: "derived",
  },
];

function question(
  itemId: string,
  order: number,
  originalText: string,
  russianText: string,
  scaleKey: string,
  scientificScale: string,
) {
  return {
    blockId: "ipip-ipc" as const,
    itemId,
    order,
    originalText,
    russianText,
    scaleKey,
    scientificScale,
    reverseKeyed: false,
    source: {
      ...IPIP_IPC_SOURCE,
      usageNotes: `${IPIP_IPC_SOURCE.usageNotes} Octant assignments follow ${IPIP_IPC_SCORING_SOURCE_URL}; axis geometry follows ${IPIP_IPC_ANGLE_REFERENCE_URL}.`,
    },
  };
}

export const IPIP_IPC_BLOCK: BlockDefinition = {
  id: "ipip-ipc",
  order: 2,
  title: "Межличностный стиль",
  subtitle: "IPIP-IPC short form",
  description:
    "Блок описывает предпочитаемый стиль контакта с людьми через восемь секторов межличностного круга и две сводные оси.",
  disclosure:
    "Это открытый межличностный опросник из пула IPIP. Русские формулировки в этом продукте адаптированы из английского оригинала и используются как рабочий интерфейсный перевод.",
  scales: IPIP_IPC_SCALES,
  questions: [
    question("1", 1, "Am quiet around strangers.", "С незнакомыми людьми я веду себя тихо.", "FG", "Aloof-Introverted"),
    question("2", 2, "Speak softly", "Я обычно говорю негромко.", "HI", "Unassured-Submissive"),
    question("3", 3, "Tolerate a lot from others", "Я многое терплю со стороны других.", "JK", "Unassuming-Ingenuous"),
    question("4", 4, "Am interested in people", "Мне по-настоящему интересны люди.", "LM", "Warm-Agreeable"),
    question("5", 5, "Feel comfortable around people", "Я чувствую себя свободно среди людей.", "NO", "Gregarious-Extraverted"),
    question("6", 6, "Demand to be the center of interest", "Мне важно оказываться в центре внимания.", "PA", "Assured-Dominant"),
    question("7", 7, "Cut others to pieces", "В разговоре я могу жёстко разнести другого.", "BC", "Arrogant-Calculating"),
    question("8", 8, "Believe people should fend for themselves", "Я считаю, что каждый должен сам справляться со своими трудностями.", "DE", "Cold-Hearted"),
    question("9", 9, "Am a very private person", "Я довольно закрытый человек.", "FG", "Aloof-Introverted"),
    question("10", 10, "Let others finish what they are saying", "Я обычно даю другим договорить.", "HI", "Unassured-Submissive"),
    question("11", 11, "Take things as they come", "Я скорее принимаю происходящее, чем спорю с ним.", "JK", "Unassuming-Ingenuous"),
    question("12", 12, "Reassure others", "Я умею успокаивать других.", "LM", "Warm-Agreeable"),
    question("13", 13, "Start conversations", "Я часто сам(а) начинаю разговор.", "NO", "Gregarious-Extraverted"),
    question("14", 14, "Do most of the talking", "Нередко именно я говорю больше остальных.", "PA", "Assured-Dominant"),
    question("15", 15, "Contradict others", "Я часто возражаю другим.", "BC", "Arrogant-Calculating"),
    question("16", 16, "Don't fall for sob-stories", "Меня трудно растрогать чужими жалобами.", "DE", "Cold-Hearted"),
    question("17", 17, "Don't talk a lot", "Я не очень разговорчив(а).", "FG", "Aloof-Introverted"),
    question("18", 18, "Seldom toot my own horn", "Я редко подчёркиваю собственные заслуги.", "HI", "Unassured-Submissive"),
    question("19", 19, "Think of others first", "Я часто в первую очередь думаю о других.", "JK", "Unassuming-Ingenuous"),
    question("20", 20, "Inquire about others' well-being", "Я интересуюсь тем, как чувствуют себя другие.", "LM", "Warm-Agreeable"),
    question("21", 21, "Talk to a lot of different people at parties", "На встречах и вечеринках я легко общаюсь с разными людьми.", "NO", "Gregarious-Extraverted"),
    question("22", 22, "Speak loudly", "Я обычно говорю громко.", "PA", "Assured-Dominant"),
    question("23", 23, "Snap at people", "Я могу резко сорваться на человека.", "BC", "Arrogant-Calculating"),
    question("24", 24, "Don't put a lot of thought into things", "Я не склонен(на) долго вникать в чужие сложности.", "DE", "Cold-Hearted"),
    question("25", 25, "Have little to say", "Обычно мне немного что сказать.", "FG", "Aloof-Introverted"),
    question("26", 26, "Dislike being the center of attention", "Мне не нравится быть в центре внимания.", "HI", "Unassured-Submissive"),
    question("27", 27, "Seldom stretch the truth", "Я редко приукрашиваю правду.", "JK", "Unassuming-Ingenuous"),
    question("28", 28, "Get along well with others", "Я обычно легко лажу с другими.", "LM", "Warm-Agreeable"),
    question("29", 29, "Love large parties", "Мне нравятся большие компании и шумные встречи.", "NO", "Gregarious-Extraverted"),
    question("30", 30, "Demand attention", "Я требую к себе внимания.", "PA", "Assured-Dominant"),
    question("31", 31, "Have a sharp tongue", "У меня бывает колкий язык.", "BC", "Arrogant-Calculating"),
    question("32", 32, "Am not interested in other people's problems", "Мне не особенно интересны чужие проблемы.", "DE", "Cold-Hearted"),
  ],
};
